### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rayslxu** [Stanford-Mobisocial-IoT-Lab/thingpedia-common-devices#15]
1. nest thermostat change heat_cool to auto
2. change wsj sections to enum
3. maybe change wapo blog to string? (too many underscores and blog names are not easy to understand)
4. add "call uber"

**Comment by gcampax** [comment]
3 is tricky, because we need the exact names of the blogs to find the right xml feed url
really, i'd rather we fixed the underscores mess instead (it should not be hard to just split enums on underscores; i thought we did that in most places)

**Comment by gcampax** [comment]
We added "call uber", and we changed wsj.
The nest thermostat change should not matter.

The Wapo blog stuff maybe would be better as entity rather than enum, but the difference is small and the cost of migrating now is annoying so let's not do it.
