### ISSUE TITLE
Error in Washington Post / RSS

### ISSUE THREAD

**Issue by gcampax** [Stanford-Mobisocial-IoT-Lab/thingpedia-common-devices#41]
Washingtonpost ⇒ Notification had an error: parsed.rss.channel[0].item is not iterable.

**Comment by rayslxu** [comment]
RSS feed also doesn't work for ArXive. I think we need to switch to libraries like feedpaser to provide a more robust parser for RSS, Atom, and RDF feed

**Comment by gcampax** [comment]
Yeah that makes sense. Do you know of a good RSS parsing library that is not huge? RSS is included in every thingpedia client, I'd like to avoid MBs of dependencies.

**Comment by gcampax** [comment]
(Also no weird deps on expat or libxml2 or other C libraries like some XML parsers have)

**Comment by rayslxu** [comment]
Done.
