### ISSUE TITLE
Transfer ownership of cs294s-spr18 devices

### ISSUE THREAD

**Issue by gcampax** [Stanford-Mobisocial-IoT-Lab/thingpedia-common-devices#45]
Devices contributed by cs294s students that have agreed to it should be transferred to the Almond Authors organization (org id = 1)
- [x] Wunderlist
- [x] Google Contacts (should also switch to our OAuth Client ID)
- [x] Wolfram Alpha
- [x] Spotify (PR #44)

Everything else should be deleted.

**Comment by gcampax** [comment]
Should we also move the code for the migrated devices to our repository?

**Comment by rayslxu** [comment]
done
